package com.example.hitprojectanimals;

public class MyDataEn {
    static String[] nameArray = {"Land turtle", "Snake or dragon?", "Hai Ramon - Hai Desert Garden", "Mount Meron Nature Reserve", "Coral Beach Nature Reserve", "Hai Bar Nature Reserve in Carmel", "Majarsa Nature Reserve - Mouth of Daliot River","Shikma Sea Reserve","Between the Persian Donkey and the Carmel Ram - A Recommendation for a Hiking Trail at Hai Bar Carmel Nature Reserve","Between burrows and hills - a recommendation for a day trip to the Adullam Grove Nature Reserve and Beit Guvrin National Park"};
    static String[] description = {"In Israel, there are two species of land turtle: the desert land turtle and the common land turtle. The common turtle is the most common of them and is found in most parts of the country.", "The horned achen is a relative of the common viper, and accordingly is also equipped with long venom teeth that it uses for hunting and self-defense. If at this stage of reading you are already imagining unpleasant encounters – you will be happy to know that you have no reason to be afraid, since he lives with us only in the sands of the western Negev, and you are unlikely to encounter him on a walk with the dog.", "The Ramon fauna is a living desert garden where the opportunity is given to see in their natural habitat the small animals", "Mount Meron Nature Reserve is the largest in the north of the country. Soaring mountains, dense woodland, unique plants and animals, springs, caves and scenic views for the most part – all these are waiting for you at the top of the Galilee.", "One of the most beautiful marine reserves in the world – colorful underwater gardens.  The reefs of the Gulf of Eilat are the only coral reefs in our country, where you can observe a wonderful and colorful world of corals, fish and a huge variety of unique animals ", " Bar in Carmel\n" +
            "History, Heritage, Nature\n" +
            "The wildlife in the Carmel is dedicated to raising endangered or extinct animals from the area and returning them to the wild. There are breeding nuclei of the Persian donkey, the carmel deer, as well as vultures and birds of prey, which are also part of the project to return to the wild.", "A unique meeting point that drains into the delta that was created there of some of the important Golan rivers on their way to the Sea of Galilee. The impressive confluence of the steep slopes that slide into the delta and the influence of the flowing water make the reserve a natural treasure that preserves a succession of habitats and a variety of animals.","The Shikma Sea Reserve protects the sandy bottom and the animals that live there. It is the southernmost marine reserve in Israel on the shores of the Mediterranean Sea. Sea turtles emerge from the nests on the shores of the reserve and reach its waters before reaching the open sea.","The wildlife in the Carmel is a unique place dedicated to a noble cause: raising endangered or extinct animals from the area and returning them to the wild.","From the scenic observations we can see the special character of the Judean Plain, which combines natural areas covered with Mediterranean woodland with extensive agricultural areas, settlements and ancient remains. In the Judean Lowlands, on our itinerary, an ecological \"corridor\" passes, which allows open passage between the desert book and the Mediterranean region for animals and vegetation."};
    static Integer[] drawableArray = {R.drawable.a, R.drawable.b, R.drawable.c,
            R.drawable.d, R.drawable.e, R.drawable.f, R.drawable.g, R.drawable.h, R.drawable.i, R.drawable.j};

    static Integer[] id_ = {0, 1, 2, 3, 4, 5, 6,7,8,9};
}
